on:
  webhook:
    method: post
jobs:
  patchitem:
    name: Patch item
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.8.1
        id: api
        with:
          url: 'https://api.webflow.com/collections/617b60c3b5eba242c8571499/items/617b60c555f22dfbcbd9893c'
          bearerToken: ${{ secrets.API_KEY }}
          method: 'PATCH'
          customHeaders: '{ "accept-version": "1.0.0", "content-type":"application/json" }'
          data: '{ "fields": { "name": "Marcel" } }'
      - name: Show Response
        run: echo ${{ steps.api.outputs.response }}
