on:
  webhook:
    method: post
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        uses: actionsflow/axios@v1
        id: api
        with:
          url: https://api.webflow.com/collections/617b60c3b5eba242c8571499/items/617b60c555f22dfbcbd9893c
          method: 'PATCH'
          content-type: application/json
          headers: '{ "accept-version": "1.0.0" }'
          params: '{ "live": "true", "access_token": ${{ secrets.API_KEY }} }'
          data: '{ "fields": { "name": "Marcel" } }'
